### ISSUE TITLE
Make code pip installable

### ISSUE THREAD

**Issue by cthoyt** [rdkit/AutomatedSeriesClassification#1]
Hi, I think your notebook is really interesting! Would you be willing to accept a PR that makes the code in this repository pip installable so it's easier for others to reuse?

I've made PRs on lots of repositories with scientific code, and will do my best to explain what I did so you can learn something

**Comment by iwatobipen** [comment]
Hi @cthoyt ,
That's wonderful!
If we can install it with pip and use more easily, it seems very useful.
PR is really appreciated.
Thanks.
